tasks:
  # Add tasks here...
  - source: tasks/01-agent.py
    name: create-agents
    params: 
      data_folder: "{{cwd}}/original-data"
    product: 
      nb: "tasks-nb/01-agent.ipynb"
      agent_table: "data-products/agent.csv"
      collection_table: "data-products/collection.csv"
  - source: tasks/02-entities.py
    name: create-entities
    params: 
      data_folder: "{{cwd}}/original-data"
      dataset_id: conabio_bees
    product: 
      nb: "tasks-nb/02-entitties.ipynb"
      entity_table: "data-products/entity.csv"
      material_entity_table: "data-products/material_entity.csv"
      entity_relationship_table: "data-products/entity_relationship.csv"
  - source: tasks/03-location.py
    name: create-location
    params: 
      data_folder: "{{cwd}}/original-data"
    product: 
      nb: "tasks-nb/03-location.ipynb"
      location_table: "data-products/location.csv"
      georeference_table: "data-products/georeference.csv"
  - source: tasks/04-events-occurrences.py
    name: create-events-occurrences
    params: 
      data_folder: "{{cwd}}/original-data"
      dataset_id: conabio_bees
    product: 
      nb: "tasks-nb/04-events-occurrences.ipynb"
      events_table: "data-products/event.csv"
      occurrence_table: "data-products/occurrence.csv"
      occurrence_evidence: "data-products/occurrence_evidence.csv"

  - source: tasks/05-taxa.py
    name: create-taxa
    params: 
      data_folder: "{{cwd}}/original-data"
    product: 
      nb: "tasks-nb/05-taxa.ipynb"
      taxon_table: "data-products/taxon.csv"

  - source: tasks/06-organism-identification.py
    name: set-identification
    params: 
      data_folder: "{{cwd}}/original-data"
    product: 
      nb: "tasks-nb/06-organism-identification.ipynb"
      organism_table: "data-products/organism.csv"
      identification_table: "data-products/identification.csv"
      taxon_identification_table: "data-products/taxon_identification.csv"
